In [51]:
import pandas as pd

rev1 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 1.csv', encoding='latin1')
rev2 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 2.csv', encoding='latin1')
rev3 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 3.csv', encoding='latin1')
rev4 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 4.csv', encoding='latin1')
rev5 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 5.csv', encoding='latin1')
rev6 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 6.csv', encoding='latin1')
rev7 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 7.csv', encoding='latin1')
rev8 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 8.csv', encoding='latin1')
rev9 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 9.csv', encoding='latin1')
rev10 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 10.csv', encoding='latin1')
rev11 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 11.csv', encoding='latin1')
rev12 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 12.csv', encoding='latin1')
rev13 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 13.csv', encoding='latin1')
rev14 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 14.csv', encoding='latin1')
rev15 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 15.csv', encoding='latin1')
rev16 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 16.csv', encoding='latin1')
rev17 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 17.csv', encoding='latin1')
rev18 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 18.csv', encoding='latin1')
rev19 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 19.csv', encoding='latin1')
rev20 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 20.csv', encoding='latin1')
rev21 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 21.csv', encoding='latin1')
rev22 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 22.csv', encoding='latin1')
rev23 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 23.csv', encoding='latin1')
rev24 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 24.csv', encoding='latin1')
rev25 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Review 25.csv', encoding='latin1')


concatenated_df = pd.concat([rev1, rev2, rev2, rev3, rev4, rev5, rev6, rev7, rev8, rev9, rev10, rev11, rev12, rev13, rev14, rev15, rev16, rev17, rev18, rev19, rev20, rev21, rev22, rev23, rev24, rev25])

concatenated_df.drop("Unnamed: 0", axis=1, inplace=True)

file_path = 'C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\concat_hotel_reviews.csv'

concatenated_df.to_csv(file_path, index=False)

print(f"Data saved to '{file_path}'")

Data saved to 'C:\Users\Arboy\Desktop\SP702\Capstone\Task 1\concat_hotel_reviews.csv'

In [52]:
concatenated_df = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\concat_hotel_reviews.csv')

print("DataFrame Information:")
print(concatenated_df.info())

print("\nMissing Values per Column:")
print(concatenated_df.isnull().sum())

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 529 entries, 0 to 528
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Hotel Name  520 non-null    object
 1   Author      514 non-null    object
 2   Country     517 non-null    object
 3   Review      517 non-null    object
dtypes: object(4)
memory usage: 16.7+ KB
None

Missing Values per Column:
Hotel Name     9
Author        15
Country       12
Review        12
dtype: int64

In [53]:
concatenated_df.dropna(inplace=True)

concatenated_df.reset_index(drop=True, inplace=True)

file_path2 = 'C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\cleaned_hotel_reviews.csv'

concatenated_df.to_csv(file_path2, index=False)

print(f"Data saved to '{file_path2}'")

Data saved to 'C:\Users\Arboy\Desktop\SP702\Capstone\Task 1\cleaned_hotel_reviews.csv'

In [54]:
source = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel Source.csv', encoding='latin1')

print("DataFrame Information:")
print(source.info())

print("\nMissing Values per Column:")
print(source.isnull().sum())

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Hotel Name       40 non-null     object
 1   Address          40 non-null     object
 2   Barangay         33 non-null     object
 3   City Town        40 non-null     object
 4   Province         40 non-null     object
 5   Amenities        40 non-null     object
 6    Price Range     36 non-null     object
 7   Available Rooms  40 non-null     int64
 8   Other Data       40 non-null     object
 9   Reviews          40 non-null     int64
dtypes: int64(2), object(8)
memory usage: 3.3+ KB
None

Missing Values per Column:
Hotel Name         0
Address            0
Barangay           7
City Town          0
Province           0
Amenities          0
 Price Range       4
Available Rooms    0
Other Data         0
Reviews            0
dtype: int64

In [55]:
source.dropna(inplace=True)

source.reset_index(drop=True, inplace=True)

filtered_df = source[source['Reviews'] > 30].head(25)

print("Filtered DataFrame Information:")
print(filtered_df.info())

print("\nFiltered DataFrame (First 25 hotels):")
print(filtered_df)

Filtered DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
Int64Index: 25 entries, 0 to 26
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Hotel Name       25 non-null     object
 1   Address          25 non-null     object
 2   Barangay         25 non-null     object
 3   City Town        25 non-null     object
 4   Province         25 non-null     object
 5   Amenities        25 non-null     object
 6    Price Range     25 non-null     object
 7   Available Rooms  25 non-null     int64
 8   Other Data       25 non-null     object
 9   Reviews          25 non-null     int64
dtypes: int64(2), object(8)
memory usage: 2.1+ KB
None

Filtered DataFrame (First 25 hotels):
                                           Hotel Name  \
0             Cauayan Island Resort and Spa (El Nido)
2                            Vellago Resort (El Nido)
3                       Club Paradise Palawan (Coron)
4                     Two Seasons Coron Island Resort
5                                 Nacpan Beach Resort
6                                     Astoria Palawan
7   Hue Hotels and Resorts Puerto Princesa Managed...
8                                       LIHIM RESORTS
9                   Daluyon Beach and Mountain Resort
10                               Panja Resort Palawan
11                                  Buko Beach Resort
12                                 Frangipani El Nido
13                                    Matinloc Resort
14                             Bacau Bay Resort Coron
15                         Carpe Diem Villas & Resort
16                                        Lagun Hotel
18                                         Tag Resort
19                                           Seda Lio
20                             The Funny Lion - Coron
21                                    Munting Paraiso
22                                Corto del Mar Hotel
23                               Coron Westown Resort
24              Princesa Garden Island Resort and Spa
25                    Two Seasons Coron Bayside Hotel
26                               Aziza Paradise Hotel

                                              Address                Barangay  \
0   Cauayan Island, Bacuit Bay, Palawan, 5313 El N...  Buena Suerte Poblacion
2   Outside El Nido Town Proper, Seven Commando Be...  Buena Suerte Poblacion
3    Dimakya Island, Palawan, 5316 Coron, Philippines                San Jose
4   Malaruyroy, Bulalacao, Palawan, 5316 Bulalacao...               Bulalacao
5   Nacpan Beach, Barangay Bucana, 5313 El Nido, P...                  Bucana
6    Km 62 North National Highway, Barangay San Ra...              San Rafael
7   Km. 3 Puerto Princesa North Road, Brgy. San Ma...              San Manuel
8   999 Sitio Caalan, Brgy. Masagana, 5313 El Nido...                Masagana
9   Sabang Beach, Sitio Sabang, Barangay Cabayugan...               Cabayugan
10  Bay Vista Road, Barangay Tagburos, Palawan, 53...                Tagburos
11  Lot 10, Sitio Lugadia, Barangay Corong Corong,...           Corong Corong
12  National Highway, Barangay Corong Corong, Pala...           Corong Corong
13  Matinloc Island, Palawan, 5313 El Nido, Philip...               Bebeladan
14  Governor's Drive, Sitio Jolo, Poblacion 5, Pal...              Barangay V
15  F. Ponce de Leon Road, 5300 Puerto Princesa, P...               San Pedro
16  Balinsasayaw Road, Barangay Maligaya, National...                Maligaya
18  National Highway Sitio Dipulao, Barangay Pobla...             Barangay VI
19  Lio Tourism Estate, Barangay Villa Libertad, P...          Villa Libertad
20  Sitio Jolo, Poblacion V, Palawan, Coron Town P...              Barangay V
21  Abueg Road, Bancao Bancao, Palawan, 5300 Puert...           Bancao Bancao
22  Commiseria Street Barangay 1, Coron Town Prope...              Barangay I
23  Sitio Dipulao, Barangay Poblacion 6, 5316 Coro...             Barangay VI
24  Barangay Bancao-bancao, Caniguiran, Palawan, 5...           Bancao Bancao
25  National Road, Barangay Tagumpay, Palawan, Cor...                Tagumpay
26  BM Road, Barangay San Manuel, Palawan, 5300 Pu...              San Manuel

          City Town Province  \
0           El Nido  Palawan
2           El Nido  Palawan
3             Coron  Palawan
4             Coron  Palawan
5           El Nido  Palawan
6   Puerto Princesa  Palawan
7   Puerto Princesa  Palawan
8           El Nido  Palawan
9   Puerto Princesa  Palawan
10  Puerto Princesa  Palawan
11          El Nido  Palawan
12          El Nido  Palawan
13          El Nido  Palawan
14            Coron  Palawan
15  Puerto Princesa  Palawan
16          El Nido  Palawan
18            Coron  Palawan
19          El Nido  Palawan
20            Coron  Palawan
21  Puerto Princesa  Palawan
22            Coron  Palawan
23            Coron  Palawan
24  Puerto Princesa  Palawan
25            Coron  Palawan
26  Puerto Princesa  Palawan

                                            Amenities  Price Range   \
0   Outdoor swimming pool\nAirport shuttle\nNon-sm...     35,530.00
2   Airport shuttle\nRoom service\nRestaurant\nBea...     27,880.00
3   Outdoor swimming pool\nAirport shuttle (free)\...     12,525.00
4   Outdoor swimming pool\nAirport shuttle (free)\...     27,000.00
5   Outdoor swimming pool\nAirport shuttle\nFree p...      8,640.00
6   Outdoor swimming pool\nAirport shuttle\nFitnes...      4,344.00
7   Outdoor swimming pool\nNon-smoking rooms\nFitn...      3,137.00
8   Outdoor swimming pool\nAirport shuttle (free)\...     39,286.00
9   Outdoor swimming pool\nAirport shuttle\nNon-sm...      6,697.00
10  Outdoor swimming pool\nSpa\nRoom service\nRest...      4,063.00
11  Outdoor swimming pool\nAirport shuttle\nRoom s...     18,400.00
12  Outdoor swimming pool\nAirport shuttle (free)\...     20,888.00
13  2 swimming pools\nAirport shuttle\nRoom servic...     15,625.00
14  Outdoor swimming pool\nAirport shuttle\nFree p...      6,885.00
15  Outdoor swimming pool\nAirport shuttle\nNon-sm...      5,100.00
16  Outdoor swimming pool\nAirport shuttle\nFree p...      4,786.00
18  Outdoor swimming pool\nAirport shuttle\nFree p...      5,656.00
19  Outdoor swimming pool\nAirport shuttle\nFree p...     13,819.00
20  Outdoor swimming pool\nAirport shuttle\nFree p...      7,650.00
21  Outdoor swimming pool\nFitness center\nRoom se...      4,370.00
22  Outdoor swimming pool\nFree WiFi\nFamily rooms...      6,912.00
23  2 swimming pools\nWiFi\nAirport shuttle\nResta...      5,054.00
24  2 swimming pools\nFitness center\nRoom service...     10,500.00
25  Outdoor swimming pool\nAirport shuttle\nRoom s...      8,000.00
26  2 swimming pools\nAirport shuttle (free)\nFitn...      3,115.00

    Available Rooms                                         Other Data  \
0                29  Land and boat transfers\nWith Own Pier\nSolar ...
2                 6        Land and Air Transfers\nNon-smoking rooms\n
3                67        Land and Air Transfers\nNon-smoking rooms\n
4                47                             Land and Air Transfers
5                21        Land and Air Transfers\nNon-smoking rooms\n
6                76        Land and Air Transfers\nNon-smoking rooms\n
7               122  Non-smoking rooms\nFacilities for disabled guests
8                21        Land and Air Transfers\nNon-smoking rooms\n
9                24  Land and Air transfers\nNon-smoking rooms\nFac...
10               35                                Non-smoking rooms\n
11                8          Land and Air transfers\nNon-smoking rooms
12                7          Land and Air transfers\nNon-smoking rooms
13               28          Land and Air transfers\nNon-smoking rooms
14               79          Land and Air transfers\nNon-smoking rooms
15               11  Land and Air transfers\nNon-smoking rooms\nNew...
16               37          Land and Air transfers\nNon-smoking rooms
18               78          Land and Air transfers\nNon-smoking rooms
19              152          Land and Air transfers\nNon-smoking rooms
20               45          Land and Air transfers\nNon-smoking rooms
21               12          Land and Air transfers\nNon-smoking rooms
22               17                                  Non-smoking rooms
23               76          Land and Air transfers\nNon-smoking rooms
24               68          Land and Air transfers\nNon-smoking rooms
25               54          Land and Air transfers\nNon-smoking rooms
26              128          Land and Air transfers\nNon-smoking rooms

    Reviews
0       149
2        72
3       323
4        64
5       360
6       264
7       853
8        46
9        47
10      302
11      116
12       69
13       93
14      363
15       54
16      255
18      350
19      283
20      352
21      275
22      531
23      226
24       98
25      329
26      706

In [56]:
import pandas as pd

df1 = filtered_df
df2 = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\cleaned_hotel_reviews.csv', encoding='latin1')

merged_df = pd.merge(df1, df2, on='Hotel Name', how='left')

file_path3 = 'C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel.csv'

merged_df.to_csv(file_path3, index=False)

print(f"Data saved to '{file_path3}'")

Data saved to 'C:\Users\Arboy\Desktop\SP702\Capstone\Task 1\Hotel.csv'

In [57]:
merged = pd.read_csv('C:\\Users\\Arboy\\Desktop\\SP702\\Capstone\\Task 1\\Hotel.csv', encoding='latin1')

print("DataFrame Information:")
print(merged.info())

print("\nMissing Values per Column:")
print(merged.isnull().sum())

DataFrame Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 504 entries, 0 to 503
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Hotel Name       504 non-null    object
 1   Address          504 non-null    object
 2   Barangay         504 non-null    object
 3   City Town        504 non-null    object
 4   Province         504 non-null    object
 5   Amenities        504 non-null    object
 6    Price Range     504 non-null    object
 7   Available Rooms  504 non-null    int64
 8   Other Data       504 non-null    object
 9   Reviews          504 non-null    int64
 10  Author           504 non-null    object
 11  Country          504 non-null    object
 12  Review           504 non-null    object
dtypes: int64(2), object(11)
memory usage: 51.3+ KB
None

Missing Values per Column:
Hotel Name         0
Address            0
Barangay           0
City Town          0
Province           0
Amenities          0
 Price Range       0
Available Rooms    0
Other Data         0
Reviews            0
Author             0
Country            0
Review             0
dtype: int64